/**
 * @file Generated by js-routes 2.3.6. Based on Rails 8.1.2 routes of RailsInertiaTemplate::Application.
 * @version a9aef596810c23d9ee73ab7fff0fb9e6301b73a3cf92c6fb13cc96467c468f93
 * @see https://github.com/railsware/js-routes
 */
declare type Optional<T> = {
  [P in keyof T]?: T[P] | null
}
declare type Collection<T> = Record<string, T>
declare type BaseRouteParameter = string | boolean | Date | number | bigint
declare type MethodRouteParameter = BaseRouteParameter | (() => BaseRouteParameter)
declare type ModelRouteParameter =
  | {
      id: MethodRouteParameter
    }
  | {
      to_param: MethodRouteParameter
    }
  | {
      toParam: MethodRouteParameter
    }
declare type RequiredRouteParameter = BaseRouteParameter | ModelRouteParameter
declare type OptionalRouteParameter = undefined | null | RequiredRouteParameter
declare type QueryRouteParameter =
  | OptionalRouteParameter
  | QueryRouteParameter[]
  | {
      [k: string]: QueryRouteParameter
    }
declare type RouteParameters = Collection<QueryRouteParameter>
declare type Serializable = Collection<unknown>
declare type Serializer = (value: Serializable) => string
declare type RouteHelperExtras = {
  requiredParams(): string[]
  toString(): string
}
declare type RequiredParameters<T extends number> = T extends 1
  ? [RequiredRouteParameter]
  : T extends 2
    ? [RequiredRouteParameter, RequiredRouteParameter]
    : T extends 3
      ? [RequiredRouteParameter, RequiredRouteParameter, RequiredRouteParameter]
      : T extends 4
        ? [
            RequiredRouteParameter,
            RequiredRouteParameter,
            RequiredRouteParameter,
            RequiredRouteParameter,
          ]
        : RequiredRouteParameter[]
declare type RouteHelperOptions = RouteOptions & Collection<OptionalRouteParameter>
declare type RouteHelper<T extends number = number> = ((
  ...args: [...RequiredParameters<T>, RouteHelperOptions]
) => string) &
  RouteHelperExtras
declare type RouteHelpers = Collection<RouteHelper>
declare type Configuration = {
  prefix: string
  default_url_options: RouteParameters
  special_options_key: string
  serializer: Serializer
}
interface RouterExposedMethods {
  config(): Configuration
  configure(arg: Partial<Configuration>): Configuration
  serialize: Serializer
}
declare type KeywordUrlOptions = Optional<{
  host: string
  protocol: string
  subdomain: string
  port: string | number
  anchor: string
  trailing_slash: boolean
  script_name: string
  params: RouteParameters
}>
declare type RouteOptions = KeywordUrlOptions & RouteParameters
declare type PartsTable = Collection<{
  r?: boolean
  d?: OptionalRouteParameter
}>
declare type ModuleType = 'CJS' | 'AMD' | 'UMD' | 'ESM' | 'DTS' | 'NIL'
declare const RubyVariables: {
  PREFIX: string
  DEPRECATED_FALSE_PARAMETER_BEHAVIOR: boolean
  DEPRECATED_NIL_QUERY_PARAMETER_BEHAVIOR: boolean
  SPECIAL_OPTIONS_KEY: string
  DEFAULT_URL_OPTIONS: RouteParameters
  SERIALIZER: Serializer
  ROUTES_OBJECT: RouteHelpers
  MODULE_TYPE: ModuleType
  WRAPPER: <T>(callback: T) => T
}
declare const define:
  | undefined
  | (((arg: unknown[], callback: () => unknown) => void) & {
      amd?: unknown
    })
declare const module:
  | {
      exports: unknown
    }
  | undefined
export const configure: RouterExposedMethods['configure']

export const config: RouterExposedMethods['config']

export const serialize: RouterExposedMethods['serialize']

/**
 * Generates rails route to
 * /users/cancel(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const cancelUserRegistrationPath: ((
  options?: { format?: OptionalRouteParameter } & RouteOptions
) => string) &
  RouteHelperExtras

/**
 * Generates rails route to
 * /users/sign_out(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const destroyUserSessionPath: ((
  options?: { format?: OptionalRouteParameter } & RouteOptions
) => string) &
  RouteHelperExtras

/**
 * Generates rails route to
 * /items/:id/edit(.:format)
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const editItemPath: ((
  id: RequiredRouteParameter,
  options?: { format?: OptionalRouteParameter } & RouteOptions
) => string) &
  RouteHelperExtras

/**
 * Generates rails route to
 * /users/password/edit(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const editUserPasswordPath: ((
  options?: { format?: OptionalRouteParameter } & RouteOptions
) => string) &
  RouteHelperExtras

/**
 * Generates rails route to
 * /users/edit(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const editUserRegistrationPath: ((
  options?: { format?: OptionalRouteParameter } & RouteOptions
) => string) &
  RouteHelperExtras

/**
 * Generates rails route to
 * /inertia-example(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const inertiaExamplePath: ((
  options?: { format?: OptionalRouteParameter } & RouteOptions
) => string) &
  RouteHelperExtras

/**
 * Generates rails route to
 * /items/:id(.:format)
 * @param {any} id
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const itemPath: ((
  id: RequiredRouteParameter,
  options?: { format?: OptionalRouteParameter } & RouteOptions
) => string) &
  RouteHelperExtras

/**
 * Generates rails route to
 * /items(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const itemsPath: ((options?: { format?: OptionalRouteParameter } & RouteOptions) => string) &
  RouteHelperExtras

/**
 * Generates rails route to
 * /items/new(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const newItemPath: ((
  options?: { format?: OptionalRouteParameter } & RouteOptions
) => string) &
  RouteHelperExtras

/**
 * Generates rails route to
 * /users/password/new(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const newUserPasswordPath: ((
  options?: { format?: OptionalRouteParameter } & RouteOptions
) => string) &
  RouteHelperExtras

/**
 * Generates rails route to
 * /users/sign_up(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const newUserRegistrationPath: ((
  options?: { format?: OptionalRouteParameter } & RouteOptions
) => string) &
  RouteHelperExtras

/**
 * Generates rails route to
 * /users/sign_in(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const newUserSessionPath: ((
  options?: { format?: OptionalRouteParameter } & RouteOptions
) => string) &
  RouteHelperExtras

/**
 * Generates rails route to
 * /
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const rootPath: ((options?: RouteOptions) => string) & RouteHelperExtras

/**
 * Generates rails route to
 * /users/auth/google_oauth2(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const userGoogleOauth2OmniauthAuthorizePath: ((
  options?: { format?: OptionalRouteParameter } & RouteOptions
) => string) &
  RouteHelperExtras

/**
 * Generates rails route to
 * /users/auth/google_oauth2/callback(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const userGoogleOauth2OmniauthCallbackPath: ((
  options?: { format?: OptionalRouteParameter } & RouteOptions
) => string) &
  RouteHelperExtras

/**
 * Generates rails route to
 * /users/password(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const userPasswordPath: ((
  options?: { format?: OptionalRouteParameter } & RouteOptions
) => string) &
  RouteHelperExtras

/**
 * Generates rails route to
 * /users(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const userRegistrationPath: ((
  options?: { format?: OptionalRouteParameter } & RouteOptions
) => string) &
  RouteHelperExtras

/**
 * Generates rails route to
 * /users/sign_in(.:format)
 * @param {object | undefined} options
 * @returns {string} route path
 */
export const userSessionPath: ((
  options?: { format?: OptionalRouteParameter } & RouteOptions
) => string) &
  RouteHelperExtras
