// Typelizer digest 4322171d2a030e0ab4bdad969ad3a0b2
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Item = {
  id: number;
  name: string;
  description: string | null;
  phoneNumber: string | null;
  createdAt: string;
  updatedAt: string;
}

export default Item;
