// Typelizer digest 85c0353d5e1312e3aa541eec3507d362
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Item = {
  id: string;
  name: string;
  description: string | null;
  phoneNumber: string | null;
  createdAt: string;
  updatedAt: string;
}

export default Item;
