// TypesFromSerializers CacheKey f0ecad62c5f3978bb13eb40ddf05aa95
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Item {
  id: number
  createdAt: string | Date
  description?: string
  name: string
  updatedAt: string | Date
}
