// Typelizer digest e43377cdac53787b672be85579b70bc2
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Item, Pagy} from '@/types'

type ItemsIndex = {
  items: Array<Item>;
  pagy: Pagy;
}

export default ItemsIndex;
