// Typelizer digest 6c29094e22f01326ebcc17bb19484f94
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Pagy = {
  count: number;
  page: number;
  limit: number;
  pages: number;
  last: number;
  in: number;
  from: number;
  to: number;
  next: number | null;
  prev: number | null;
}

export default Pagy;
