// Typelizer digest 279928be709e39cd4e064d5913723df4
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type User = {
  id: number;
  name: string | null;
  email: string;
  avatarUrl: string | null;
}

export default User;
