// Typelizer digest c82d679a0a4e29be90451fcdbbfc8d7d
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {User, Pagy} from '@/types'

type UsersIndex = {
  users: Array<User>;
  pagy: Pagy;
}

export default UsersIndex;
