// Typelizer digest 87bbc070152f43087ac8b8ddf8e21a8d
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type User = {
  id: string;
  name: string | null;
  email: string;
  avatarUrl: string | null;
  createdAt: string;
  roles: Array<string>;
  itemsCount: number;
}

export default User;
