// Typelizer digest 0761d618afd8e9c786c71ed6f9c86a0d
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type User = {
  id: string;
  name: string | null;
  email: string;
  avatarUrl: string | null;
  createdAt: string;
  roles: Array<string>;
}

export default User;
