// Typelizer digest a12cfc44ea92840011ce00a3693e9eed
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Version = {
  id: number;
  itemType: string;
  itemId: number;
  event: string;
  createdAt: string;
  object: Record<string, unknown> | null;
  objectChanges: Record<string, [unknown, unknown]> | null;
}

export default Version;
