// Typelizer digest 5f7d5d68a5e782ba11e2e90b11473aac
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Version = {
  id: string;
  itemType: string;
  itemId: string;
  event: string;
  createdAt: string;
  object: Record<string, unknown> | null;
  objectChanges: Record<string, [unknown, unknown]> | null;
}

export default Version;
