// Typelizer digest d9ff47687c6d1ea3c2dbb9d657559ab9
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Version, Pagy} from '@/types'

type VersionsIndex = {
  versions: Array<Version>;
  pagy: Pagy;
}

export default VersionsIndex;
